---
application:
  name: "space-server"
  project: "space-server"
  organization: "QoveryCommunity"
routers:
- name: "main-space-server"
  routes:
  - application_name: "space-server"
    paths:
    - "/*"
